[package]
name = "mmcupdater-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
axum = { version = "0.4", features = ["multipart"] }
base32 = "0.4"
bytes = { version = "1.1", features = [] }
csv-async = { version = "1.2", features = ["tokio"] }
dotenv = "0.15"
futures = "0.3"
hex = "0.4"
log = { version = "0.4", features = ["release_max_level_info"] }
md5 = { version = "0.7", features = [] }
once_cell = "1.9"
parking_lot = "0.12"
rand = { version = "0", features = [] }
regex = { version = "1.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.16", features = ["rt-multi-thread", "fs", "process", "macros", "sync", "parking_lot", "io-util"] }
toml = { version = "0.5", features = [] }
tower = "0.4"
tower-http = { version = "0.2", features = ["fs", "cors"] }
tracing = "0.1"
tracing-subscriber = "0.3"
zip = "0.5"